Fix carthage build error in v5.5.1 and v5.5.2
Carthage build has been broken since v5.5.1 due to the updates on build script.
The error looks like the following:

```
$ carthage build --no-skip-current --platform iOS

(omitted)

Downloading dependency: sync 5.0.33 from https://static.realm.io/downloads/sync/realm-sync-xcframework-5.0.33.tar.xz
ld: building for iOS Simulator, but linking in .tbd built for macOS/Mac Catalyst, file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build system
note: Using codesigning identity override:
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
error: There is no XCFramework found at '/Users/kiyotaka.sasaya/devel/realm-cocoa/core/realm-sync.xcframework'. (in target 'Realm iOS static' from project 'Realm')

** ARCHIVE FAILED **
```

Using xcrun for clang++ invocation solves this error.